---
# Dataset
dataset: Sbank # Mohler, Sbank
graph_file: Dataset/scientsbank/GT_graphs/data.bin
graph_info_file: Dataset/scientsbank/GT_graphs/data.pkl
shuffle: True

model_dir: model/Sbank_prunned_class

# Train parameter
mode: classification # regression, classification
n_class: 5
batch_size: 32
val_split: 0.2
epochs: 500
init_lr: 0.0007
weight_decay: 0.0
lr_reduce_factor: 0.5
lr_schedule_patience: 25

# pytorch
device: gpu # auto, gpu, cpu.
seed: 56339

# Model configurations
num_vocab: 2000 # 2000 / 20001
num_edge_type: 30 # 30 / 45
hidden_dim: 64 # original 64
num_heads: 8
out_dim: 64 #  original 64
in_feat_dropout: 0.0
dropout: 0.0
num_layers: 10
readout: mean
layer_norm: False
batch_norm: True
residual: True
edge_feat: True
lap_pos_enc: True
wl_pos_enc: False
pos_enc_dim: 8