---
# Dataset
graph_file: Dataset/mohler/GT_graphs/data.bin
graph_info_file: Dataset/mohler/GT_graphs/data.pkl
shuffle: True

model_dir: model/graphTrans_regress

# Train parameter
batch_size: 32
val_split: 0.2
epochs: 500
init_lr: 0.0007
weight_decay: 0.0
lr_reduce_factor: 0.5
lr_schedule_patience: 15

# pytorch
device: gpu # auto, gpu, cpu.
seed: 56339

# Model configurations
num_vocab: 20001
num_edge_type: 45
hidden_dim: 64
num_heads: 8
out_dim: 64
in_feat_dropout: 0.0
dropout: 0.0
num_layers: 10
readout: mean
layer_norm: False
batch_norm: True
residual: True
edge_feat: True
lap_pos_enc: True
wl_pos_enc: False
pos_enc_dim: 8