---
# Dataset
graph_file: Dataset/mohler/GT_graphs/data.bin
graph_info_file: Dataset/mohler/GT_graphs/data.pkl
shuffle: True

# Train parameter
batch_size: 4
val_split: 0.2

# pytorch
device: auto # auto, gpu, cpu.
seed: 56339

# Model configurations
num_vocab: 10000
num_edge_type: 40
hidden_dim: 64
num_heads: 8
out_dim: 64
in_feat_dropout: 0.0
dropout: 0.0
num_layers: 10
readout: mean
layer_norm: False
batch_norm: True
residual: True
edge_feat: True
lap_pos_enc: True
wl_pos_enc: False
pos_enc_dim: 8